### ISSUE TITLE
There was an error with your serialport module, Pymakr will likely not work properly.

### ISSUE THREAD

**Issue by MJtuks** [pycom/pymakr-vsc#62] opened 2019-10-30 14:28 UTC
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

## What are the steps to reproduce this issue?
1. Install Pymakr on VSCode
2.
3.

## What happens?
An error pops up.

## What were you expecting to happen?
I was expecting no error to pop up.

## Any logs, error output, etc?
There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)

https://gist.github.com/MJtuks/6e16d397690be9a67418b5fec4e54e01

## What versions of software are you using?

**Operating system:**
Windows 10

**VSCode version:**
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Pymakr version:**
1.1.3

**Comment by poesel** [comment] 2019-11-09 10:30
Same problem here, only VSC 1.4 as of today.
Tried uninstall/install to no avail.
Any idea how to fix this?

**Comment by William04A** [comment] 2019-11-09 12:13
I have gotten this problem now as well.
Sorry, but a similar problem with updates was happening with Atom, and now with VS Code?
PyCom, I think you should look over how your extension works with new versions of VS before they are rolled out to everyone...

**Comment by GC-RnD** [comment] 2019-11-09 13:11
There was an error with your serialport module

cause...
Visual Studio Code
latest update October 2019 (version 1.40)
added Electron 6.0 Update
breaks serialport bindings (again)

**VSC About**
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Pycom... please give this your utmost attention. 
This is making extremely difficult developing our Gpy product.

**Comment by William04A** [comment] 2019-11-09 13:30
Yes, it really does. I am also developing a product and having to switch between versions, code editors and enable/disabled settings and updates you want to have is inconvenient.

You are not superheroes, but all we are asking for is a more stable plugin that works when new official versions for code editors. Also, faster response for official statements on this and what you are doing to fix the issue (this took several weeks for you this summer)

**Comment by Jerremy09** [comment] 2019-11-09 15:14
Hi same issue with:

**VSCode:**
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Issues**:
"There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)"

**PyMakr Version:** 1.1.4

Can you please take a look?

Thank you

**Comment by ttadam** [comment] 2019-11-09 20:42
Same issue for me also.

**Comment by Jdam0xff** [comment] 2019-11-09 21:14
Same issue:

> There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)

VSCode:
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-32-generic snap

**Comment by ekendra-nz** [comment] 2019-11-10 00:05
Same. No connection.

**Comment by Josverl** [comment] 2019-11-10 11:54
FYI, this is being worked on,
my TLDR on the cause : 
* A recent update of VSCode to electron to  6.1.2 from 4.x.x requires new native binaries for the serialport/bindings; ABI version 73 
* This is caused by an underlying architctural issue recognized by NodeJS/Electron in the fact  the Application Binary Interface is not upward compatible between versions, but no final solution has been accepted by the ecosystem. 
* The published serialport binaries for ABI 73 were actually corrupt and not working, this was reported , but not resolved 
* Pycom was working to integrate a longterm solution to this problem into Pymakr vsc, but VSCode released before this was ready 

Currently looking at alternatives to either :
- precompile them for all 5+ platforms ( win/linux/mac * 32/64 bit) 
- move to a new version of the serialport bin and hope/test that these work better 

meanwhile  the below instructions proved to work for most people as a temp workaround:
 
for windows : 
``` powershell
npm install -g prebuild-install
cd %userprofile%\.vscode\extensions\pycom.pymakr-1.1.2
cd node_modules\@serialport\bindings
prebuild-install --runtime electron --target 6.1.2 --tag-prefix @serialport/bindings@ --verbose --force

```

For *nix/Mac:
``` bash
npm install -g prebuild-install
cd ~\.vscode\extensions\pycom.pymakr-1.1.2
cd node_modules\@serialport\bindings
prebuild-install --runtime electron --target 6.1.2 --tag-prefix @serialport/bindings@ --verbose --force
```

**Comment by GC-RnD** [comment] 2019-11-10 12:12
Jos,

I am using pycom.pymakr-1.1.4
and this fix did not work


PS C:\Users\Rich\.vscode\extensions\pycom.pymakr-1.1.4\node_modules\@serialport\bindings> npm install -g prebuild-install
C:\Users\Rich\AppData\Roaming\npm\prebuild-install -> C:\Users\Rich\AppData\Roaming\npm\node_modules\prebuild-install\bin.js
+ prebuild-install@5.3.3
updated 1 package in 1.732s

PS C:\Users\Rich\.vscode\extensions\pycom.pymakr-1.1.4\node_modules\@serialport\bindings> prebuild-install --runtime electron --target 6.1.2 --tag-prefix @serialport/bindings@ --verbose --force
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install WARN install prebuilt binaries enforced with --force!
prebuild-install WARN install prebuilt binaries may be out of date!
prebuild-install info looking for cached prebuild @ C:\Users\Rich\AppData\Roaming\npm-cache\_prebuilds\f3b07b-bindings-v2.0.8-electron-v73-win32-x64.tar.gz
prebuild-install http request GET https://github.com/node-serialport/node-serialport/releases/download/@serialport/bindings@2.0.8/bindings-v2.0.8-electron-v73-win32-x64.tar.gz
prebuild-install http 404 https://github.com/node-serialport/node-serialport/releases/download/@serialport/bindings@2.0.8/bindings-v2.0.8-electron-v73-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=6.1.2 runtime=electron arch=x64 libc= platform=win32)

**Comment by Josverl** [comment] 2019-11-10 12:52
Note in advance: Your milage **will** vary on the OS and what you may or may not have pre-installed. 
the below steps are (in my opinion) exactly what should be avoided for end-users , but what is quite complex to avoid in a multiplatform javascript + native world.



```
npm install -g electron-rebuild
cd ~\.vscode\extensions\pycom.pymakr-1.1.4
electron-rebuild --version 6.1.2 --force
```
Note when using Windows cmd replace `~` by `%userprofile%`

![Manual-Fix](https://user-images.githubusercontent.com/981654/68544162-92387880-03c0-11ea-83f7-3f58cac5595e.gif)

**Comment by Jdam0xff** [comment] 2019-11-10 13:02
I found a 

> Note in advance: Your milage **will** vary on the OS and what you may or may not have pre-installed.
> the below steps are (in my opinion) exactly what should be avoided for end-users , but what is quite complex to avoid in a multiplatform javascript + native world.
> 
> ```
> npm install -g electron-rebuild
> cd ~\.vscode\extensions\pycom.pymakr-1.1.4
> electron-rebuild --version 6.1.2 --force
> ```
> 
> Note when using Windows cmd replace `~` by `%userprofile%`
> 
> ![Manual-Fix](https://user-images.githubusercontent.com/981654/68544162-92387880-03c0-11ea-83f7-3f58cac5595e.gif)
> 
> Also note that electron-rebuild requires a looooong list of prereqs ( compilers , toolchains) to be installed.
> Each OS / Distro / version has its own way to install these, and some installations of the compilers and libraries components and and patches can be very complex indeed.
> 
> So if this fails that does not mean that there is anything wrong with your computer, it just means that is not set up as a development environment ( which is probably good)

Damn you are fast.

Second "solution" is to downgrade vs code version, with electron: 4.x.x
![image](https://user-images.githubusercontent.com/26165538/68544339-6b7b4180-03c2-11ea-809d-74a96a7bc50e.png)

**Comment by Josverl** [comment] 2019-11-10 13:15
if the above workd for you , you could do all other users a huge favor if you can share the compiled binaries for your OS/bitness. 
These will be located in the folder:
` ~\.vscode\extensions\pycom.pymakr-1.1.4\node_modules\@serialport\bindings\build\release` 
while we actually only need 1 file ('bindings.node') it may be simplest to just put the entire folder in a . zip file  (or any other archive / tarball that works for you ) and share that.
please also add the  OS / Version  / bitness ( vscode > Help > About ) 

I can collect them and put them in for an interim build/release 
we need:  
* Windows (aka win32)
  -  x64 - Done 
  -  ia32
* Linux 
  -  x64 
  -  ia32
* Mac (aka darwin) 
  -  x64 

I was working on these , but i hope collectively we can move even faster

**Comment by GC-RnD** [comment] 2019-11-10 13:30
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:01:56.781Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT ia32 6.1.7601          Windows 7 Ultimate did not fix


Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763       Windows 10 Pro did fix

**Comment by BradenM** [comment] 2019-11-10 18:58
@Josverl, 

What do you think about setting up a CI workflow that would:
1. Execute on push to master branch
2. Check if the bindings need updating (do you have a method for automating this?)
3. If so, compile bindings for each OS (parallel jobs)
4. If successful, commit them back to master branch automatically.

If you know of a solid method of testing whether an update is necessary or not, I could definitely write something up in Git actions or Travis.

**Comment by Josverl** [comment] 2019-11-10 20:43
I have a partial solution for Pymakr-vsc not loading after a recent update of VScode , most recently to electron 6.1.2 
I have included bindings for:
OS | x64 | ia32 | comments |
----|------|------|--------------|
Windows | Yes  | Yes | ia32 compiled on x64 using NVM for windows to switch node architecture 
Linux | Yes | **no** 😢 | I have no ia32 environment to run electron-rebuild --version 6.1.2 --force 
MacOS | **no** 😭 |  | I have no MacOS environment to run electron-rebuild --version 6.1.2 --force 

Note: very limited testing 🐱‍💻, so please be let me know gently when it does not work.
https://github.com/Josverl/pymakr-vsc/releases/download/v1.1.5/pymakr-1.1.5-beta.vsix

**Comment by Josverl** [comment] 2019-11-10 20:52
> @Josverl,
> 
> What do you think about setting up a CI workflow that would:
> 
> 1. Execute on push to master branch
> 2. Check if the bindings need updating (do you have a method for automating this?)
> 3. If so, compile bindings for each OS (parallel jobs)
> 4. If successful, commit them back to master branch automatically.
> 
> If you know of a solid method of testing whether an update is necessary or not, I could definitely write something up in Git actions or Travis.

Hi Braden, yep some sort of automation would be needed, this is no task for humans.
I've got a lot of bits and pieces, but was waiting for Pycom to take ownership as I have a day-job as well ;-) .
I'm confident that is now happening with a Pedro @ pycom taking over maintenance. 
I thin it makes sense to run a separate issue to work on the automated tests

**Comment by Jerremy09** [comment] 2019-11-10 22:58
Hi,

looks like the version 1.1.5 works for me (pymakr Loaded after VS Code Turn on): 
**Windows:** Windows 10

**VS Code:**
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by rodgergr** [comment] 2019-11-11 06:39
Hi,

1.1.5 works for me too on Windows 10 x64 with VSCode 1.40.0.

Just launching the VSIX file on its own did not find VSCode properly and threw an error. However,  using View/Extensions in VSCode, hitting the upper right '...' in the extensions frame, and then "Install from VSIX..." did the trick.

Thanks @Josverl

**Comment by pedroknup** [comment] 2019-11-11 09:54
I'm working on it. The current version (1.1.4) is working on macOS and linux x64. It seems the 1.1.5 version by @Josverl is working on Windows, so if you guys are using Windows, I suggest you download it. 

I'm also working on a definitive working around for this, dealing with pipelines and a smarter solution for the serialport library. @Josverl has been helping me with that, so you can expect good stuff :P

**Comment by pedroknup** [comment] 2019-11-11 11:53
Just released 1.1.5 that might work for every OS and architecture but Linux x86.

**Comment by GC-RnD** [comment] 2019-11-11 11:59
1.1.5 Also works for me....
OS: Windows_NT ia32 6.1.7601   Windows 7 Ultimate NOW FIXED!!

Thank you

**Closed** 2019-11-25 15:17 UTC

**Comment by neil9** [comment] 2021-07-10 05:21
Yeah well you Pycom guys - its STILL NOT WORKING. Come on Pycom - if you release a product on the market its a good idea that it works !!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by huwei1024** [comment] 2021-07-12 15:26
not working on Mac m1

**Comment by g88827929g** [comment] 2021-08-06 11:24
its still not working on vscode 1.59.0

**Comment by Josverl** [comment] 2021-08-06 11:30
@g88827929g Please open a new issue if you have similar problems , and add the VScode & Pymakr  version details to that issue.

this issue for the versions mentioned above is fixed, its just that you now have another version of VSCode , and that makes a big difference.

**Comment by keagster** [comment] 2021-10-05 06:48
Crew, This really needs a long-term stable solution. Just ask us to open tickets every time VSC gets updated isn't a solution (@Josverl ). I purchased this device as I thought it would remove the barrier to entry to start working with LoRa on our projects. Now I have to spend time rewriting crap. Even Pycom had to be refactored because you used async as a module name. 

Please reach out if you need some assistance getting all these repos in order. If I find a workaround I will post.

**Comment by jakobrosenberg** [comment] 2021-10-05 08:36
@keagster thanks for reaching out. Would you be interested in trying this beta and reporting back? https://github.com/pycom/pymakr-vsc/releases/tag/v1.1.14-beta.0

It's the first release that automatically downloads the correct bindings.

Unfortunately there are no available bindings for ARM yet. We're currently looking into solutions for this.

**Comment by Josverl** [comment] 2021-10-05 10:34
@keagan,

I'm not working for pycom , im just a guy that is trying to help the community. 
Just a bit of research would have told you that
if you take offence at me trying to provide guidance  provide effective feedback, rather than respond to closed issues with demands, then I really do not have any suggestions left.

**Comment by BNS-Ichthus** [comment] 2021-10-09 14:45
Had the same issue; installing the beta release listed above solved the problem for me!

**Comment by keagster** [comment] 2021-10-10 03:52
I managed to get around to testing this. 
- Removed Pymakr
- Cleaned up .vscode
- Installed beta from VSIX
- Reloaded

Still encountering the same error regarding my serial module. What i have checked so far:
- Serial permissions
- Hardware
- System logs

Nothing appears to be failing on the system at all have used this machine to work with hundreds of devices like this and never faced any programming or serial issues. The system is Arch Linux running kernel 5.4.148. Do you have any advice on getting this to work?
