### ISSUE TITLE
[BUG] Adding device in File Explorer doesn't work

### ISSUE THREAD

**Issue by maihde** [pycom/pymakr-vsc#241] opened 2022-05-24 12:51 UTC
**Describe the bug**
Using PyMakr-VSC and clicking the "Open device in file explorer" I get a proper serial port in the explorer but it has an error.

**To Reproduce**
1. In the PyMakr panel connect to a device
2. Click on 'Open device in file explorer'
3. Open Explorer

**Expected behavior**
The device folder opens and shows the contents of the device.

**Screenshots**
![image](https://user-images.githubusercontent.com/229922/170038883-a949720e-2d2e-49d9-ad48-e9f94eea83ca.png)

**Desktop (please complete the following information):**
 - OS: Win 11 x86_64
 - Device ESP32 Huzzah
 - Pymakr v2.13.2

**Comment by maihde** [comment] 2022-05-24 12:54
After some investigation, might be related to https://github.com/pycom/pymakr-vsc/discussions/224 since I'm running MicroPython.

**Comment by maihde** [comment] 2022-05-25 01:46
My workaround was this:

1. %USERPROFILE%/.vscode/extensions\pycom.pymakr-preview-2.13.2/package.json
2. Find the line that looks like `"match": "serialNumber=Example1234",`
3. Change the serialNumber to match your board, change the value to `/`

**Comment by jakobrosenberg** [comment] 2022-05-30 06:31
Thanks for posting your solution @maihde.

I'm closing this as the issue is resolved.

**Closed by jakobrosenberg** 2022-05-30 06:31 UTC
